'\" t
.\"     Title: helper.sh
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Helper.sh Manual
.\"    Source: Helper.sh 0.1.0
.\"  Language: English
.\"
.TH "HELPER.SH" "7" "2021-12-31" "Helper.sh 0.1.0" "Helper.sh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
helper.sh \- helper shell library (sets bash strict mode by default)
.SH "SYNOPSIS"
.sp
.nf
\fBhelper.sh\fP [\fIOPTION\fP]... [\fIOPTION PROGRAM OUTPUT\fP]... \fIARGUMENT\fP...
.fi
.br
.sp
\fBhelper.sh\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.SH "DESCRIPTION"
.sp
The \fBhelper.sh\fP library when \fIsourced\fP:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
set bash strict mode, the default (STRICT=0 . \fBhelper.sh\fP to not set strict mode),
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
set helper \fIfunctions\fP
.br
.RE
.sp
When \fIexecuted\fP:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
updates itself (\fIlib\fP option) by calling \fIcolor(1)\fP or shows the output (\fIno options\fP)
of all colors and helper functions,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
shows the output (\fIno options\fP) of all colors and helper functions,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
and shows \fIProgram Information\fP.
.RE
.SH "ARGUMENTS"
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "THE DEBUG HELPER"
.sp
\fI$\fP DEBUG=1 \fBdebug\fP VARIABLE1 VARIABLE2
.SH "THE DIE HELPER"
.sp
\fI$\fP false || \fBdie\fP Error Message
.br
\fI$\fP \fBdie\fP Task Completed
.SH "THE ERROR HELPER"
.sp
\fI$\fP \fBerror\fP Error Message
.SH "THE HAS HELPER"
.sp
\fI$\fP \fBhas\fP git
.br
\fI$\fP \fBhas\fP \fI\-p\fP git
.br
\fI$\fP \fBhas\fP \fI\-pv\fP git
.SH "THE PARSE HELPER"
.sp
\fI$\fP \fBparse\fP "${arg}"
.SH "THE PSARGS HELPER"
.sp
\fI$\fP \fBpsargs\fP
.SH "THE SUCCESS HELPER"
.sp
\fI$\fP \fBsuccess\fP Success Message
.SH "THE VERBOSE HELPER"
.sp
\fI$\fP VERBOSE=1 \fBverbose\fP Verbose Message
.br
\fI$\fP DRY_RUN=1 \fBverbose\fP Dry\-run Message
.SH "THE WARNING HELPER"
.sp
\fI$\fP WARNING=1 \fBwarning\fP Warning Message
.SH "EXAMPLES"
.sp
.nf
\fI$\fP . \fBhelper.sh\fP
.fi
.br
.sp
\fI$\fP STRICT=0 . \fBhelper.sh\fP
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
debug(1), die(1), error(1), has(1), parse(1), psargs(1), success(1), verbose(1), warning(1)
.SH "AUTHOR"
.sp
j5pu