#!/bin/sh

#
# binpm installer
set -eu

if [ "$(basename "$0")" = 'install' ]; then
  downloaded=true
else
  downloaded=false
fi

echo "$downloaded"
#cd "$(basename "${0}")"
#pwd
#PATH="${PWD}:${PATH}"
