#!/bin/sh

#
# binpm installer
set -eu

name='binpm'

if [ "$(basename "$0")" = 'install' ]; then
  downloaded=true
  ! command -v "${name}" >/dev/null || PATH="$(dirname "$0"):${PATH}"
else
  downloaded=false
fi

echo "$downloaded"
