'\" t
.\"     Title: color
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Color Manual
.\"    Source: Color 0.1.0
.\"  Language: English
.\"
.TH "COLOR" "1" "2021-12-31" "Color 0.1.0" "Color Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
color \- show colors and helper functions output, or generate color lib
.SH "SYNOPSIS"
.sp
.nf
\fBcolor\fP [\fIOPTION\fP] [\fIOPTION PROGRAM OUTPUT\fP]
\fBcolor\fP lib
\fBcolor\fP
\fBcolor\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBcolor\fP command generates (\fIlib\fP option) the \fIcolor.sh(7)\fP library with:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fIglobals\fP for colors: \fI$ColorFormat\fP,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
and \fIfunctions\fP colors: \fIcolorformat()\fP
.RE
.sp
and shows the output (\fIno options\fP) of all colors and helper functions.
.SH "OPTIONS"
.sp
\fBlib\fP
.RS 4
Generates the \fIcolor.sh(7)\fP library.
.RE
.SH "ARGUMENTS"
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBcolor\fP
.fi
.br
.sp
\fI$\fP \fBcolor\fP \fIlib\fP
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
color.sh(7)
.SH "AUTHOR"
.sp
j5pu