'\" t
.\"     Title: colon
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-29
.\"    Manual: Colon Manual
.\"    Source: Colon 0.1.0
.\"  Language: English
.\"
.TH "COLON" "1" "2021-12-29" "Colon 0.1.0" "Colon Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
colon \- Prepend (beginning, the default), append (end) or remove to colon variables (PATH, INFOPATH, MANPATH etc.)
.SH "SYNOPSIS"
.sp
.nf
\fBcolon\fP [\fIOPTION\fP]... [\fIFILE|DIR\fP] [\fIVALUE\fP]
\fBcolon\fP \-\-base
\fBcolon\fP \-\-bins [\fIFILE|DIR\fP]
\fBcolon\fP \-\-init
.fi
.br
.sp
\fBcolon\fP \-\-description|\-\-name|\-\-subsections|\-\-synopsis|\-\-desc|\-\-help|\-\-manrepo|\-\-version|...
.SH "DESCRIPTION"
.sp
The \fBcolon\fP command with no arguments will show with export command \fBcleaned\fP \fI$PATH\fP, \fI$MANPATH\fP and \fI$INFOPATH\fP
variables of directories which do not exist. The output can be used with \fIeval\fP.
When \fIFILE\fP is provided in the \fIFILE|DIR\fP argument, it\(cqs parent is used as directory.
.br
The default is to \fIprepend\fP the \fIFILE|DIR\fP to \fIVALUE\fP.
.br
.sp
The \fI\-\-base\fP, \fI\-\-bins\fP and \fI\-\-init\fP options imply
the \fI\-\-export\fP option and show the output
for \fI$PATH\fP, \fI$MANPATH\fP and \fI$INFOPATH\fP, ready for \fIeval\fP.
.SH "OPTIONS"
.sp
\fB\-\-append\fP
.RS 4
Append \fIFILE|DIR\fP argument (dirname if \fIFILE\fP)
to \fIVALUE\fP argument (if provided, otherwise returns the \fIFILE|DIR\fP argument).
.RE
.sp
\fB\-\-base\fP
.RS 4
Shows the base \fI$PATH\fP, \fI$MANPATH\fP and \fI$INFOPATH\fP with \fI/\fP and \fI/usr\fP
as top directories to add:
\fI/bin\fP, \fI/sbin\fP, \fI/share/man\fP and \fI/share/info\fP.
.br
It implies the \fI\-\-export\fP option to be used with \f(CReval\fP.
.RE
.sp
\fB\-\-bins\fP
.RS 4
The output (\fI\-\-export\fP option implied) will have \fI$PATH\fP, \fI$MANPATH\fP and \fI$INFOPATH\fP updated to be used with \fIeval\fP.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
If \fBFILE|DIR\fP argument is a \fBDIR\fP, then \fBDIR\fP is prepended  to \fI$PATH\fP (unless \fBDIR\fP is the top of a git repository).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
If \fBFILE|DIR\fP argument is a \fBFILE\fP, then \fBparent of FILE\fP is prepended to \fI$PATH\fP
(unless \fBparent of FILE\fP is the top of a git repository).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fIgit top\fP if no \fBFILE|DIR\fP argument is provided
or parent directory of one of the two previous bullet items is used
to add: \fI/bin\fP, \fI/sbin\fP, \fI/share/man\fP and \fI/share/info\fP to \fI$PATH\fP,
\fI$MANPATH\fP (even if directory does not exist, since contents are generated)
and \fI$INFOPATH\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
If a \fI./tests\fP directory exists, then previous bullet items subdirectories will be added with \fI./tests/\fP.
.RE
.RE
.sp
\fB\-\-export\fP, *\-\-export=*\fI[VARIABLE NAME]\fP
.RS 4
Show the output with \fIexport command\fP to be used with \fIeval\fP with \fIVARIABLE NAME\fP if provided (default: \fI$PATH\fP).
.RE
.sp
\fB\-\-init\fP
.RS 4
Shows initial \fI$PATH\fP, \fI$MANPATH\fP, and \fI$INFOPATH\fP.
.br
It also shows:  \fI$TOP\fP and \fI$<REPO_BASENAME>_TOP\fP which contain the \fIgit top\fP for \fBcolon\fP command.
.br
It implies the \fI\-\-export\fP option to be used with \f(CReval\fP.
.RE
.sp
\fB\-P\fP, \fB\-\-physical\fP
.RS 4
Use physical absolute directories instead of symlink \fIpwd \-P\fP.
.RE
.sp
\fB\-\-remove\fP
.RS 4
Remove \fIFILE|DIR\fP argument (dirname if \fIFILE\fP)
from \fIVALUE\fP argument (if provided, otherwise returns empty).
.RE
.SH "ARGUMENTS"
.sp
\fBFILE|DIR\fP
.RS 4
Dirname of \fIFILE\fP will be used if \fIFILE|DIR\fP argument is \fIFILE\fP.
.RE
.sp
\fBVALUE\fP
.RS 4
Colon type variable value: i.e: "${PATH}"
.RE
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show man page and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show version from man page and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.SH "ENVIRONMENT"

.SH "OUTPUT"
.sp
For more information, see: \fIProgram Information\fP
\&.
.SH "EXAMPLES"
.sp
.nf
\fI$\fP eval "$(\fBcolon\fP \-\-base)"
\fI$\fP eval "$(\fBcolon\fP \-\-init)"
\fI$\fP eval "$(\fBcolon\fP)"
\fI$\fP eval "$(\fBcolon\fP \-\-init \-P)"
\fI$\fP eval "$(\fBcolon\fP \-\-bins)"
\fI$\fP eval "$(\fBcolon\fP \-\-bins .)"
\fI$\fP eval "$(\fBcolon\fP \-\-bins "$0")"
\fI$\fP PATH="$(\fBcolon\fP . "${PATH}")"
\fI$\fP eval "$(\fBcolon\fP . "${PATH}" \-\-export)"
\fI$\fP PATH="$(\fBcolon\fP \-\-append . "${PATH}")"
\fI$\fP PATH="$(\fBcolon\fP \-\-remove . "${HOME}")"
.fi
.br
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
genman(1), parse(1), parse\-man(1)
.SH "AUTHOR"
.sp
j5pu