'\" t
.\"     Title: debug
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Debug Manual
.\"    Source: Debug 0.1.0
.\"  Language: English
.\"
.TH "DEBUG" "1" "2021-12-31" "Debug 0.1.0" "Debug Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
debug \- show info message with > symbol in grey bold if DEBUG is set to 1, unless QUIET is set to 1
.SH "SYNOPSIS"
.sp
.nf
\fBdebug\fP [\fIOPTION\fP]... [\fIOPTION PROGRAM OUTPUT\fP]... [\fIVARIABLE\fP]...
\fBdebug\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBdebug\fP command will show values of \fIVARIABLES\fP option in \fI$GreyDim\fP when \fI$DEBUG\fP is set to \fI1\fP.
.br
.sp
The output will be prefixed with caller function name and line if \fI$BASH_VERSION\fP.
.SH "OPTIONS"
.sp
\fBVARIABLE\fP
.RS 4
Variable name.
.RE
.SS "Program Output"
.sp
\fB\-\-debug\fP
.RS 4
Show debug output.
.RE
.sp
\fB\-\-dry\-run\fP
.RS 4
Show verbose output and do not execute the command.
.RE
.sp
\fB\-\-no\-quiet\fP
.RS 4
Do not silent output for commands with default quiet mode, i.e.: git\-top, etc.
.RE
.sp
\fB\-\-quiet\fP
.RS 4
Silent output.
.RE
.sp
\fB\-\-warning\fP
.RS 4
Show warnings.
.RE
.sp
\fB\-\-white\fP
.RS 4
Show captured output with no color.
.RE
.sp
\fB\-\-verbose\fP
.RS 4
Verbose output.
.RE
.SH "ARGUMENTS"
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "ENVIRONMENT"
.SS "Program Output"
.sp
You can control output information using the options listed under \fIProgram Output\fP,
or using the following environment variables:
.br
.sp
\fBDEBUG\fP
.RS 4
Set \fBDEBUG\fP=\fI1\fP for debug output (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBDRY_RUN\fP
.RS 4
Set \fBDRY_RUN\fP=\fI1\fP for verbose output and do not execute the command (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBNO_QUIET\fP
.RS 4
Set \fBNO_QUIET\fP=\fI1\fP to not silent output for commands with default quiet mode, i.e.: git\-top, etc. (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBQUIET\fP
.RS 4
Set \fBQUIET\fP=\fI1\fP to silent output,
\fBQUIET\fP takes precedence over \fIDEBUG\fP, \fIVERBOSE\fP and \fIWARNING\fP.
.RE
.sp
\fBVERBOSE\fP
.RS 4
Set \fBVERBOSE\fP=\fI1\fP to show verbose messages (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBWARNING\fP
.RS 4
Set \fBWARNING\fP=\fI1\fP to show warning messages (\fIdefault\fP: \fI0\fP).
.RE
.SH "OUTPUT"
.sp
For more information, see: \fIProgram Information\fP
and to control output, see: \fIProgram Output\fP and \fIEnvironment Program Output\fP
\&.
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBdebug\fP
.fi
.br
.sp
\fI$\fP DEBUG=1 \fBdebug\fP VARIABLE1 VARIABLE2
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
helper.sh(7)
.SH "AUTHOR"
.sp
j5pu