'\" t
.\"     Title: findup
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-30
.\"    Manual: Findup Manual
.\"    Source: Findup 0.1.0
.\"  Language: English
.\"
.TH "FINDUP" "1" "2021-12-30" "Findup 0.1.0" "Findup Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
findup \- walk a file hierarchy upwards
.SH "SYNOPSIS"
.sp
.nf
\fBfindup\fP [\fIOPTION\fP]... \fIFILE|DIRECTORY\fP ... [\fIEXPRESSION\fP]...
\fBfindup\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBfindup\fP utility recursively scans \fBupwards\fP the
\fIFILE|DIRECTORY\fP (dirname of \fIFILE\fP is used, if \fIFILE|DIRECTORY\fP is a file) tree for each \fIDIRECTORY\fP listed,
evaluating an \fIEXPRESSION\fP
(composed of the “primaries” and “operands” listed in find(1)) in terms of each file in the tree.
.SH "OPTIONS"
.sp
See \fIfind(1)\fP.
.SH "ARGUMENTS"
.sp
\fBFILE|DIRECTORY\fP
.RS 4
\fIDIRECTORY\fP to walk upwards (dirname of \fIFILE\fP is used, if \fIFILE|DIRECTORY\fP
is a file)
.RE
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "EXPRESSION"
.sp
See \fIfind(1)\fP.
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
No such file or directory.
.br
.RE
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBfindup\fP .
.fi
.br
.sp
\fI$\fP \fBfindup\fP . \-name .env
.br
.sp
\fI$\fP \fBfindup\fP . \-type d \-name .git \-exec dirname "\(rs{}" \(rs; | tail \-1
.br
.sp
\fI$\fP \-H \fBfindup\fP /tmp
.br
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
find(1)
.SH "AUTHOR"
.sp
j5pu