'\" t
.\"     Title: parse
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Parse Manual
.\"    Source: Parse 0.1.0
.\"  Language: English
.\"
.TH "PARSE" "1" "2021-12-31" "Parse 0.1.0" "Parse Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
parse \- parse common long optional arguments
.SH "SYNOPSIS"
.sp
.nf
\fBparse\fP [\fIOPTION\fP]... [\fIOPTION PROGRAM OUTPUT\fP]...
\fBparse\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBparse\fP command will convert a long optional argument from \fI[_arguments\-information]\fP into a global var
(upper, \*(Aq\-\*(Aq to \*(Aq_\*(Aq and remove \*(Aq\-\-\*(Aq) and will set it to 1.
.SH "OPTIONS"
.SS "Program Output"
.sp
\fB\-\-debug\fP
.RS 4
Show debug output.
.RE
.sp
\fB\-\-dry\-run\fP
.RS 4
Show verbose output and do not execute the command.
.RE
.sp
\fB\-\-no\-quiet\fP
.RS 4
Do not silent output for commands with default quiet mode, i.e.: git\-top, etc.
.RE
.sp
\fB\-\-quiet\fP
.RS 4
Silent output.
.RE
.sp
\fB\-\-warning\fP
.RS 4
Show warnings.
.RE
.sp
\fB\-\-white\fP
.RS 4
Show captured output with no color.
.RE
.sp
\fB\-\-verbose\fP
.RS 4
Verbose output.
.RE
.SH "ENVIRONMENT"
.SS "Program Output"
.sp
You can control output information using the options listed under \fIProgram Output\fP,
or using the following environment variables:
.br
.sp
\fBDEBUG\fP
.RS 4
Set \fBDEBUG\fP=\fI1\fP for debug output (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBDRY_RUN\fP
.RS 4
Set \fBDRY_RUN\fP=\fI1\fP for verbose output and do not execute the command (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBNO_QUIET\fP
.RS 4
Set \fBNO_QUIET\fP=\fI1\fP to not silent output for commands with default quiet mode, i.e.: git\-top, etc. (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBQUIET\fP
.RS 4
Set \fBQUIET\fP=\fI1\fP to silent output,
\fBQUIET\fP takes precedence over \fIDEBUG\fP, \fIVERBOSE\fP and \fIWARNING\fP.
.RE
.sp
\fBVERBOSE\fP
.RS 4
Set \fBVERBOSE\fP=\fI1\fP to show verbose messages (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBWARNING\fP
.RS 4
Set \fBWARNING\fP=\fI1\fP to show warning messages (\fIdefault\fP: \fI0\fP).
.RE
.SH "OUTPUT"
.sp
For more information, see: \fI[_arguments\-information]\fP
.sp
and to control output, see: \fIProgram Output\fP and \fIEnvironment Program Output\fP
\&.
.SH "EXAMPLES"
.sp
.nf
case "${arg}" in
  \-\-debug|\-\-dry\-run|\-\-quiet|\-\-verbose|\-\-warning|\-\-white)
    \fBparse\fP \fI"${arg}"\fP
    shift
  *) do ;;
esac
.fi
.br
.sp
.nf
case "${arg}" in
  \-\-\fI*\fP)
    \fBparse\fP \fI"${arg}"\fP
    do other work
  *) do ;;
esac
.fi
.br
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Caution
.ps -1
.br
.sp
Do not do the following since \fI[_arguments\-information]\fP in \fI$1\fP will be treated for \fBparse\fP,
instead of the caller.
.br
.sp .5v
.RE
.sp
+
.sp
.nf
main() {
  \fBparse\fP \fI"$@"\fP
  \fBfromman\fP \fI"$0"\fP \fI"$@"\fP || exit
}
.fi
.br
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
helper.sh(7)
.SH "AUTHOR"
.sp
j5pu