'\" t
.\"     Title: psargs
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Psargs Manual
.\"    Source: Psargs 0.1.0
.\"  Language: English
.\"
.TH "PSARGS" "1" "2021-12-31" "Psargs 0.1.0" "Psargs Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
psargs \- parent process args (cmd/command and args part of ps)
.SH "SYNOPSIS"
.sp
.nf
\fBpsargs\fP [\fIARGUMENT\fP] ...
.fi
.br
.sp
\fBpsargs\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.SH "DESCRIPTION"
.sp
The \fBpsargs\fP command shows the \fIparent process args\fP (cmd/command and args part of ps)
\fIif in a subshell\fP or \fIcmd of the current shell\fP if running in a subshell.
.br
.sp
\fI$$\fP is defined to return the \fIprocess ID of the parent in a subshell\fP.
.br
.sp
From the bash(1) man page under "Special Parameters":
expands to the process ID of the shell. In a () subshell, it expands to the process ID of the current shell,
not the subshell.
.SH "ARGUMENTS"
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Error.
.br
.RE
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBpsargs\fP
.fi
.br
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
helper.sh(7)
.SH "AUTHOR"
.sp
j5pu