'\" t
.\"     Title: real
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Real Manual
.\"    Source: Real 0.1.0
.\"  Language: English
.\"
.TH "REAL" "1" "2021-12-31" "Real 0.1.0" "Real Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
real \- absolute logical (symlink) or resolved (physical) path
.SH "SYNOPSIS"
.sp
.nf
\fBreal\fP [\fIOPTION\fP]... [\fIPATH\fP]
\fBreal\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBreal\fP command will show the absolute \fIlogical/symlink\fP (default)
or the \fIresolved/physical\fP (\fI\-\-resolved\fP|\fI\-P\fP) path
of the \fIPATH\fP option (default: cwd).
.sp
If \fIPATH\fP does not exist, \fBreal\fP will not fail (unless \fI\-\-fail\fP option is used) if the parent of \fIPATH\fP exists,
the absolute path will be constructed with the dirname of \fIPATH\fP (exists) and basename of \fIPATH\fP (does not exist).
.SH "OPTIONS"
.sp
\fBPATH\fP
The absolute or relative path to use (default: cwd).
.sp
\fB\-\-dirname\fP
.RS 4
Show dirname instead of \fIPATH\fP.
.RE
.sp
\fB\-\-fail\fP
.RS 4
Exit \fI1\fP if \fIPATH\fP does not exists.
.RE
.sp
\fB\-P, \-\-resolved\fP
.RS 4
Resolve symlinks (pwd \-P).
.RE
.SS "Program Output"
.sp
\fB\-\-debug\fP
.RS 4
Show debug output.
.RE
.sp
\fB\-\-dry\-run\fP
.RS 4
Show verbose output and do not execute the command.
.RE
.sp
\fB\-\-no\-quiet\fP
.RS 4
Do not silent output for commands with default quiet mode, i.e.: git\-top, etc.
.RE
.sp
\fB\-\-quiet\fP
.RS 4
Silent output.
.RE
.sp
\fB\-\-warning\fP
.RS 4
Show warnings.
.RE
.sp
\fB\-\-white\fP
.RS 4
Show captured output with no color.
.RE
.sp
\fB\-\-verbose\fP
.RS 4
Verbose output.
.RE
.SH "ARGUMENTS"
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Directory or File not Found (\fI\-\-fail\fP option).
.br
Directory not Found.
.RE
.SH "ENVIRONMENT"
.SS "Program Output"
.sp
You can control output information using the options listed under \fIProgram Output\fP,
or using the following environment variables:
.br
.sp
\fBDEBUG\fP
.RS 4
Set \fBDEBUG\fP=\fI1\fP for debug output (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBDRY_RUN\fP
.RS 4
Set \fBDRY_RUN\fP=\fI1\fP for verbose output and do not execute the command (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBNO_QUIET\fP
.RS 4
Set \fBNO_QUIET\fP=\fI1\fP to not silent output for commands with default quiet mode, i.e.: git\-top, etc. (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBQUIET\fP
.RS 4
Set \fBQUIET\fP=\fI1\fP to silent output,
\fBQUIET\fP takes precedence over \fIDEBUG\fP, \fIVERBOSE\fP and \fIWARNING\fP.
.RE
.sp
\fBVERBOSE\fP
.RS 4
Set \fBVERBOSE\fP=\fI1\fP to show verbose messages (\fIdefault\fP: \fI0\fP).
.RE
.sp
\fBWARNING\fP
.RS 4
Set \fBWARNING\fP=\fI1\fP to show warning messages (\fIdefault\fP: \fI0\fP).
.RE
.SH "OUTPUT"
.sp
For more information, see: \fIProgram Information\fP
and to control output, see: \fIProgram Output\fP and \fIProgram Output\fP.
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBreal\fP
.fi
.br
.sp
\fI$\fP cd /; \fBreal\fP \-\-dirname tmp
.sp
\fI$\fP cd /; \fBreal\fP \-\-resolved tmp
.sp
\fI$\fP cd /; \fBreal\fP \-P tmp
.sp
\fI$\fP \fBreal\fP \-\-fail \-\-quiet foo
.sp
\fI$\fP \fBreal\fP \-\-fail \-\-resolved \-\-quiet foo
.sp
\fI$\fP \fBreal\fP \-\-fail foo
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
genman(1), fromman(1), parse(1)
.SH "AUTHOR"
.sp
j5pu