'\" t
.\"     Title: real
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-31
.\"    Manual: Real Manual
.\"    Source: Real 0.1.0
.\"  Language: English
.\"
.TH "REAL" "1" "2021-12-31" "Real 0.1.0" "Real Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
real \- Absolute logical (symlink, default) or resolved (physical, pwd \-P) path (Accepts one level up if it doesn\*(Aqt exists)
.SH "SYNOPSIS"
.sp
.nf
\fBreal\fP [\fIOPTION\fP]... [\fIPATH\fP]
\fBreal\fP \-\-desc|\-\-description|\-\-examples|\-\-help|\-\-manrepo|\-\-subsections|\-\-synopsis|\-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
The \fBreal\fP command will show the absolute \fIlogical/symlink\fP (default)
or the \fIresolved/physical\fP (\fI\-\-resolved\fP|\fI\-P\fP) path
of the \fIPATH\fP option (default: cwd).
.sp
If \fIPATH\fP does not exist, \fBreal\fP will not fail (unless \fI\-\-fail\fP option is used) if the parent of \fIPATH\fP exists,
the absolute path will be constructed with the dirname of \fIPATH\fP (exists) and basename of \fIPATH\fP (does not exist).
.SH "OPTIONS"
.sp
\fB\-\-option\fP
.RS 4
\fIOPTION\fP one option.
.RE
.SH "ARGUMENTS"
.sp
\fBARGUMENT\fP
.RS 4
Required one \fIARGUMENT\fP.
.RE
.SS "Program Information"
.sp
\fB\-\-desc\fP
.RS 4
Show one line description from \fINAME\fP section of man page and exit.
.RE
.sp
\fB\-\-description\fP
.RS 4
Show \fIDESCRIPTION\fP subsection of man page and exit.
.RE
.sp
\fB\-\-examples\fP
.RS 4
Show \fIEXAMPLES\fP subsection of man page and exit.
.RE
.sp
\fB\-\-help\fP
.RS 4
Show \fIman page\fP and exit.
.RE
.sp
\fB\-\-manrepo\fP
.RS 4
Show \fIREPOSITORY\fP name from man page and exit.
.RE
.sp
\fB\-\-subsections\fP
.RS 4
Show \fIsubsections\fP of man page and exit.
.RE
.sp
\fB\-\-synopsis\fP
.RS 4
Show \fISYNOPSIS\fP subsection of man page and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show \fIversion\fP from man page and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Error.
.br
.RE
.SH "EXAMPLES"
.sp
.nf
\fI$\fP \fBreal\fP
output
.fi
.br
.SH "REPOSITORY"
.sp
binpm
.br
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/binpm" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
genman(1), fromman(1), parse(1)
.SH "AUTHOR"
.sp
j5pu