== SYNOPSIS

[verse]
*{manname}* [_OPTION_]... [_FILE|DIR_] [_VALUE_]
*{manname}* --base
*{manname}* --bins [_FILE|DIR_]
*{manname}* --init

include::/usr/local/include/man/SYNOPSIS-OPTIONS_Information.adoc[]

== DESCRIPTION

The *{manname}* command

== OPTIONS

// tag::options[]
*--append*::
Append _FILE|DIR_ argument (dirname if _FILE_)
to _VALUE_ argument (if provided, otherwise returns the _FILE|DIR_ argument).

*--base*::
Shows the base _$PATH_, _$MANPATH_ and _$INFOPATH_ with _/_ and _/usr_
as top directories to add:
_/bin_, _/sbin_, _/share/man_ and _/share/info_. +
It implies the _--export_ option to be used with `eval`.

*--bins*::
The output (_--export_ option implied) will have _$PATH_, _$MANPATH_ and _$INFOPATH_ updated to be used with _eval_.
* If *FILE|DIR* argument is a *DIR*, then *DIR* is prepended  to _$PATH_ (unless *DIR* is the top of a git repository).
* If *FILE|DIR* argument is a *FILE*, then *parent of FILE* is prepended to _$PATH_
(unless *parent of FILE* is the top of a git repository).
* _git top_ if no *FILE|DIR* argument is provided
or parent directory of one of the two previous bullet items is used
to add: _/bin_, _/sbin_, _/share/man_ and _/share/info_ to _$PATH_,
_$MANPATH_ (even if directory does not exist, since contents are generated)
and _$INFOPATH_.
* If a _./tests_ directory exists, then previous bullet items subdirectories will be added with _./tests/_.

*--export*, *--export=*_[VARIABLE NAME]_::
Show the output with _export command_ to be used with _eval_ with _VARIABLE NAME_ if provided (default: _$PATH_).

*--init*::
Shows initial _$PATH_, _$MANPATH_, and _$INFOPATH_. +
It also shows:  _$TOP_ and _$<REPO_BASENAME>_TOP_ which contain the _git top_ for *{manname}* command. +
It implies the _--export_ option to be used with `eval`.

*-P*, *--physical*::
Use physical absolute directories instead of symlink _pwd -P_.

*--remove*::
Remove _FILE|DIR_ argument (dirname if _FILE_)
from _VALUE_ argument (if provided, otherwise returns empty).

ifdef::Output[]
include::/usr/local/include/man/OPTIONS-Output.adoc[]
endif::[]

// end::options[]

== ARGUMENTS

// tag::arguments[]

*FILE|DIR*::
Caller _$0_ (required for _--caller_ option).

*VALUE*::
Loren.

include::/usr/local/include/man/ARGUMENTS-Information.adoc[]

// end::arguments[]

== EXIT STATUS

*0*::
Success.

*1*::
Error. +

== ENVIRONMENT

ifdef::Output[]
include::/usr/local/include/man/ENVIRONMENT-Output.adoc[]
endif::[]

== OUTPUT

For more information, see: _<<_arguments-information>>_

ifdef::Output[]

and to control output, see: _<<_options_output>>_ and _<<_environment_output>>_

endif::[]

.

== EXAMPLES

[verse]
_$_ *{manname}*
output

include::/usr/local/include/man/REPOSITORY-COPYING.adoc[]

== SEE ALSO

genman(1), parse(1), parse-man(1)
