:includedir: /usr/local/include/man
== SYNOPSIS

[verse]
*{manname}* [_COMMAND|PATH_] [_OPTION_] ...
include::{includedir}/template.adoc[tag=synopsys-information]

== DESCRIPTION

The *{manname}* command will show information from man page of _COMMAND|PATH_ (default: *{manname}*),
if the first _OPTION_ (_$1_ *{manname}* and _$2_ for others) is an option in the _<<_arguments-information>>_ list.
The program will return _1_, if there is a match in _OPTION_ (_$2_), to indicate the caller to exit.


== OPTIONS

*[COMMAND|PATH]*::
_PATH_ to get name of command from basename or _COMMAND_.

include::{includedir}/template.adoc[tag=arguments-information]

== EXIT STATUS

*0*::
When called directly (_$SHLVL=2_) and an argument from:_<<_arguments-information>>_
found in _OPTION_ (_$2_) with value from man page.

*1*::
Program will return _1_ for the following conditions:
* An argument from: _<<_arguments-information>>_ found in _OPTION_, with empty value from man page
(_Value Not Found: "$\{func}", for: "$\{cmd}"_).
* An argument from:_<<_arguments-information>>_ found in _OPTION_ (_$2_),
to indicate the caller to stop parsing and exit (except when called directly (_$SHLVL=2_), which will exit with _0_).
* _man_ command not installed (_Command Not Found: man_).
* _man page_ not found for command (_Man Page Not Found: <command>_).

== EXAMPLES

=== Terminal

_$_ *{manname}* --desc +
show description, help, repository, version or subsections (SYNOPSYS, etc.) from man page

_$_ *{manname}* git --desc +
the stupid content tracker

_$_ *{manname}* bash --synopsis +
bash [options] [command_string | file]

=== Library Usage

[verse]
if [ "$(command -p basename "$0")" = 'library.sh' ]; then
  *{manname}* _function_name_ _"$@"_ || exit 0
fi

=== Script Usage: Before Parsing

[verse]
main() {
  *{manname}* _"$0"_ _"$@"_ || exit
}

=== Script Usage: Additional Long Options to Parse

[verse]
case "$\{arg}" in
  --_*_)
    if *{manname}* _"$0"_ _"$@"_; then
      do dome work for "$\{arg}"
    else
      exit 0
    fi
    ;;
  *) do ;;
esac

=== Script Usage: No Additional Long Options to Parse

[verse]
case "$\{arg}" in
  --option) do some work for --option ;;
  --_*_) *{manname}* _"$0"_ _"$@"_ || exit 0 ;;
esac

include::{includedir}/template.adoc[tag=repository-and-copying]

== SEE ALSO

genman(1), parse(1)

